sudo: required
services:
  - docker
language: node_js
node_js:
  - "6"
install:
  - docker pull jwoos/chrome_storage
  - yarn install
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
